// Read-only model checks; no browser or package dependencies.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const data = JSON.parse(fs.readFileSync(path.join(root, 'public/internal/hku-activity/ledger.json'), 'utf8'));
const controls = Object.fromEntries(['window', 'kind', 'department', 'channel', 'search', 'with-records', 'filters', 'export'].map((id) => [id, {value: id === 'window' ? '60' : ['kind', 'department', 'channel'].includes(id) ? 'all' : '', checked: false, addEventListener() {}}]));
const context = vm.createContext({URL, console, document: {getElementById: (id) => controls[id], querySelectorAll: () => [], createElement: () => ({})}, window: {addEventListener() {}}});
const script = fs.readFileSync(path.join(root, 'public/internal/hku-activity/ledger.js'), 'utf8').replace(/\ninitialize\(\);\s*$/, '\n');
vm.runInContext(script, context);
context.data = data;
vm.runInContext('state.ledger = data; state.records = deduplicate(data.activities); state.activities = state.records; state.baseActivities = state.records; state.visible = data.people;', context);
const api = vm.runInContext('({sourceChannel, canonicalUrl, validDay, windowStart, inWindow, deduplicate, groupedLeads, csvCell, csvRows, activityMatches, filters, safeLink, activityDateLabel})', context);
vm.runInContext("state.ledger = {...data, scope: {...data.scope, asOf: '2026-09-06'}};", context);
assert.equal(api.windowStart(), '2026-07-09');
assert(api.inWindow({eventDate: '2026-07-09'}));
assert(api.inWindow({eventDate: '2026-07-08', eventEndDate: '2026-07-14'}));
assert(!api.inWindow({eventDate: '2026-07-08'}));
assert(!api.inWindow({eventDate: '2026-09-07'}));
assert(!api.inWindow({eventDate: '2026'}));
assert(!api.inWindow({eventDate: '2026-08-01', eventEndDate: '2026-07-31'}));
assert(!api.validDay('2026-02-30'));
assert.equal(api.activityDateLabel({kind:'dated profile reference', status:'reference-needs-review'}), 'Profile reference dated');
assert.equal(api.activityDateLabel({dateBasis:'date-in-profile-text'}), 'Profile reference dated');
assert.equal(api.activityDateLabel({dateBasis:'publication-date'}), 'Source publication');
assert.equal(api.activityDateLabel({status:'announced'}), 'Scheduled');
assert.equal(api.activityDateLabel({dateBasis:'reported-event-date', status:'reported'}), 'Event');
controls.window.value = '30'; assert.equal(api.windowStart(), '2026-08-08'); controls.window.value = '60';
vm.runInContext('state.ledger = data;', context);
assert.equal(api.sourceChannel('https://www.arch.hku.hk/event_/instagram-workshop/'), 'faculty_web');
assert.equal(api.sourceChannel('https://www.usi.hku.hk/event/example'), 'university_news');
assert.equal(api.sourceChannel('https://hub.hku.hk/'), 'repositories');
assert.equal(api.sourceChannel('https://doi.org/10.1234/test'), 'publishers');
assert.equal(api.sourceChannel('https://api.crossref.org/works/test'), 'publishers');
assert.equal(api.sourceChannel('https://crossref.org.example.net/test'), 'other');
assert.equal(api.sourceChannel('https://www.instagram.com/test/'), 'instagram');
assert.equal(api.sourceChannel('https://instagram.com.example.net/'), 'other');
assert.equal(api.sourceChannel('javascript:alert(1)'), 'other');
assert.equal(api.sourceChannel(undefined), 'other');
assert.equal(api.sourceChannel('https://example.net/instagram'), 'other');
assert.notEqual(api.canonicalUrl('https://publisher.example/paper?id=1'), api.canonicalUrl('https://publisher.example/paper?id=2'));
assert.equal(api.canonicalUrl('https://publisher.example/paper?utm_source=feed'), 'https://publisher.example/paper');
const duplicate = api.deduplicate([{id:'a', title:'Shared', evidenceUrl:'https://example.net/a/', eventDate:'2026-09-01', personIds:['p1']}, {id:'b', title:'Shared', evidenceUrl:'https://example.net/a/#fragment', eventDate:'2026-09-01', personIds:['p2']}]);
assert.equal(duplicate.length, 1); assert.equal(duplicate[0].personIds.length, 2);
const profileReferences = api.deduplicate([{id:'p1', title:'Paper A', kind:'dated profile reference', evidenceUrl:'https://example.net/profile', eventDate:'2026-09-01'}, {id:'p2', title:'Paper B', kind:'dated profile reference', evidenceUrl:'https://example.net/profile', eventDate:'2026-08-01'}]);
assert.equal(profileReferences.length, 2, 'Different dated profile references must not collapse by shared profile URL');
assert.equal(api.groupedLeads([{publisherUrl:'https://example.net/a', personName:'A'}, {publisherUrl:'https://example.net/a', personName:'B'}]).length, 1);
assert.equal(api.csvCell('=1+1'), '"\'=1+1"'); assert.equal(api.csvCell(' \t@SUM(A1)'), '"\' \t@SUM(A1)"'); assert.equal(api.csvCell('a"b'), '"a""b"');
assert.equal(api.safeLink('bad', 'javascript:alert(1)').href, undefined);
assert.equal(api.safeLink('bad local', './../secrets.json', '', true).href, undefined);
const records = api.csvRows('records'), expectedRecords = api.deduplicate(data.activities);
assert.equal(records.length - 1, expectedRecords.length);
assert.equal(records.slice(1).filter((row) => row[2] === 'Faculty website').length, expectedRecords.filter((a) => a.sourceChannel === 'faculty_web').length);
assert.equal(records.slice(1).filter((row) => row[2] === 'University news & institutes').length, expectedRecords.filter((a) => a.sourceChannel === 'university_news').length);
assert.equal(records.slice(1).filter((row) => row[2] === 'Publishers').length, expectedRecords.filter((a) => a.sourceChannel === 'publishers').length);
const sources = api.csvRows('sources'), channelRows = sources.filter((row) => row[0] === 'Channel'), fetchRows = sources.filter((row) => row[0] === 'HTTP fetch'), leadRows = sources.filter((row) => row[0] === 'Manual lead');
assert.equal(channelRows.reduce((sum, row) => sum + row[5], 0), expectedRecords.length);
assert.equal(fetchRows.length, data.sources.length);
assert.equal(channelRows.reduce((sum, row) => sum + row[7], 0), data.sources.length);
assert.equal(fetchRows.reduce((sum, row) => sum + row[6], 0), data.sources.filter((s) => s.status === 'success').length);
const savedLeads = Array.isArray(data.publicationLeads) ? data.publicationLeads : data.publicationLeads?.leads || [];
assert.equal(leadRows.length, api.groupedLeads(savedLeads).length); assert(leadRows.every((row) => row[5] === '' && row[6] === '' && row[7] === ''));
controls.channel.value = 'publishers';
assert.equal(data.activities.filter((a) => api.activityMatches(a, api.filters())).length, data.activities.filter((a) => a.sourceChannel === 'publishers' && api.inWindow(a)).length);
controls.channel.value = 'instagram'; assert.equal(data.activities.filter((a) => api.activityMatches(a, api.filters())).length, data.activities.filter((a) => a.sourceChannel === 'instagram' && api.inWindow(a)).length);
console.log(`PASS: date boundaries, URL channels, deduplication, separate manual leads, source safety and CSV escaping; saved dataset has ${expectedRecords.length} records.`);
